Update 10812.cpp
LuckyPigeon/CPE_Previous_Questions pull request #45
Opened 2020-10-16 12:53 UTC by MinTimmy

新增註解

2020-10-16 14:03 UTC, LuckyPigeon commented on 一星題/10812/10812.cpp
> +  // 逐一處理每筆資料
@MinTimmy 
像這種一整行都沒有程式碼的註解可以幫我改成用 `/* */` 這樣的註解方式嗎？

2020-10-17 07:33 UTC, MinTimmy commented
學長我修改好了~~麻煩你看一下。

2020-10-17 07:58 UTC, LuckyPigeon requested changes

2020-10-17 07:58 UTC, LuckyPigeon commented on 一星題/10812/10812.cpp
> +  // 逐一處理每筆資料
@MinTimmy 
不是改上面的啦～😅
上方 6～10 行可以幫我還原嗎？🙏
然後把第 13 行的 `// 逐一處理每筆資料` 改成 `/* 逐一處理每筆資料 */` 嗎？感謝！🙏

2020-10-18 02:53 UTC, MinTimmy commented
學長我修改好了~~麻煩你看一下。

2020-10-18 15:24 UTC, LuckyPigeon commented
@MinTimmy 
感謝你的貢獻！🙏
這個 PR 我 Merge 囉！🎉
這個專案的首頁有 `Contributing.md`，裡面有專案註解需要的風格，有空可以去看看。對你未來工作或貢獻其他專案很有幫助喔！加油！💪

2020-10-18 15:24 UTC, merged